use_frameworks!

platform :ios, '10.0'

target 'KYLocalDataManager_Example' do
  pod 'KYLocalDataManager', :path => '../'

  target 'KYLocalDataManager_Tests' do
    inherit! :search_paths

    
  end
end
